
version: 0.2
    
phases:
  install:
    run-as: root
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    run-as: root
    commands:
      - npm run build
artifacts:
  files:
    - build/*
    - build/**/*